# Copyright (c) NiceBots
# SPDX-License-Identifier: MIT

services:
  redis:
    image: redis:alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
    ports:
      - "6379:6379"
    command: --loglevel debug