# Copyright NiceBots all rights reserved - refer to LICENSE file in the root 2025, 2026

bot:
  token: "bot token here"
use:
  backend: false
extensions:
  branding:
    enabled: false
  ping:
    enabled: false
  topgg:
    enabled: false
