# Copyright (c) NiceBots all rights reserved - refer to LICENSE file in the root

bot:
  token: "bot token here"
use:
  backend: false
extensions:
  branding:
    enabled: false
  ping:
    enabled: false
  topgg:
    enabled: false
