#file: noinspection SpellCheckingInspection
name: CI/CD

on:
  push:
    branches: [ "main", "dev" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: ["dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  docker:
    needs: tests
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yaml

  deploy:
    needs: docker
    uses: ./.github/workflows/deploy.yaml
