name: Template Sync

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.repository != 'nicebots-xyz/botkit'
    outputs:
      pr_branch: ${{ steps.template-sync.outputs.pr_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Template Sync
        id: template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: nicebots-xyz/botkit
          upstream_branch: dev
          pr_commit_msg: "core: :twisted_rightwards_arrows: Merge remote template"
          pr_title: "core: :twisted_rightwards_arrows: Merge remote template"

  update-deps:
    needs: repo-sync
    if: needs.repo-sync.outputs.pr_branch
    uses: ./.github/workflows/update_dependencies.yaml
    with:
      pr_branch: ${{ needs.repo-sync.outputs.pr_branch }}
    permissions:
      contents: write
      pull-requests: write
