name: Run Tests

on: workflow_call

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install dependencies
        run: pdm install -d
      - name: Run formatting check
        run: pdm run ruff format --check .
      - name: Run linting check
        run: pdm run ruff check .
      - name: Run tests
        run: pdm run tests